// BaseHog.idl : BaseHog 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(BaseHog.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";
import "GameData.idl";

[
	object,
	uuid(FA6B316E-BAC1-4360-A894-7783B7DF340F),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IHog : IDispatch{
	[id(1)] HRESULT BindHogData([in] PTableInfo _table, [in] PChairInfo _chairs, [in] LONG chairSum);
	[id(2)] HRESULT InitHogData([in] ENUM_HOG_STAT iniStat);
	[id(3)] HRESULT GenerateHog( [out] BOOL *next, [out] LONG *_hogID );
};
[
	uuid(6C872422-33F7-4CCA-83EF-AAEC36CD6E1A),
	version(1.0),
]
library BaseHogLib
{
	importlib("stdole2.tlb");
	[
		uuid(4E14A166-5C2E-412F-A94B-326FF50A7A59)		
	]
	coclass Hog
	{
		[default] interface IHog;
	};
};

import "shobjidl.idl";
