// CenterData.idl : CenterData 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(CenterData.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

// hs_enable 有效无效
typedef enum chair_enable
{
      CHAIR_DISABLE = 0,  // 无效
	  CHAIR_ENABLE        // 有效
}ENUM_CHAIR_ENABLE;

// hs_hot_state 表决
typedef enum hog_stat
{
      HOG_NULL = 0, // 无效
	  HOG_DOWN,     // 不抢
	  HOG_UP		// 抢
}ENUM_HOG_STAT;

// 角色
typedef enum player_role
{
      ROLE_ZHUANG = 0,
	  ROLE_XIAN
}ENUM_PLAYER_ROLE;


typedef struct _tagChairInfo 
{
	ENUM_CHAIR_ENABLE	hs_chair_enable;
	ENUM_HOG_STAT		hs_hot_state;	// 状态 未定， 叫，不叫
	ENUM_PLAYER_ROLE	hs_role;		// 角色 未定，闲， 庄
	LONGLONG			hs_chip;		// 筹
	DWORD				hs_enableHog;	// 能否Hog  FALSE--不能， TRUE---能
}ChairInfo, *PChairInfo;

// 座子信息
typedef struct _tagTableInfo 
{
	DWORD	ti_curCount; // 当前局数
	DWORD	ti_allCount; // 总局数
	LONGLONG ti_lowScore; // 底分
}TableInfo , *PTableInfo;


[
	object,
	uuid(59D8A9ED-F59B-445C-9685-22CD38469884),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IZySdn : IDispatch{
};
[
	uuid(9A0A0330-53C9-4BE8-AA74-6023CE0D1D37),
	version(1.0),
]
library CenterDataLib
{
	importlib("stdole2.tlb");
	[
		uuid(EA23FE32-4B93-478B-B2A8-7681BFA1EEB2)		
	]
	coclass ZySdn
	{
		[default] interface IZySdn;
	};
};

import "shobjidl.idl";
