// CenterData.idl : CenterData 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(CenterData.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";
import "GameData.idl";

[
	object,
	uuid(59D8A9ED-F59B-445C-9685-22CD38469884),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IZySdn : IDispatch{
	[id(1)] HRESULT CreateTable([out,retval] LONG* tableID);
	[id(2)] HRESULT Hog([in] LONG tableID, [in] LONG chairID, [in] ENUM_HOG_STAT _hog);
};
[
	uuid(9A0A0330-53C9-4BE8-AA74-6023CE0D1D37),
	version(1.0),
]
library CenterDataLib
{
	importlib("stdole2.tlb");
	[
		uuid(EA23FE32-4B93-478B-B2A8-7681BFA1EEB2)		
	]
	coclass ZySdn
	{
		[default] interface IZySdn;
	};
};

import "shobjidl.idl";
