// CenterSvr.idl : CenterSvr 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(CenterSvr.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";
import "GameData.idl";

[
	object,
	uuid(FDCF44B6-3174-4D8A-B2EF-D9A159474D49),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IQPServer : IDispatch{
	[id(1)] HRESULT Hog([in] LONG nTableID, [in] LONG nChairID, [in] ENUM_HOG_STAT _hog);
	[id(2)] HRESULT CreateSub([in] LONG subType, [in] LONG tid );
};
[
	uuid(CC506581-6450-4B04-87C9-D519EA7AFDA9),
	version(1.0),
]
library CenterSvrLib
{
	importlib("stdole2.tlb");
	[
		uuid(6370FA5B-0048-4053-B645-036909DDA673)		
	]
	coclass QPServer
	{
		[default] interface IQPServer;
	};
};

import "shobjidl.idl";
